name: wdb106_sample
description: A new Flutter project.
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
  bloc_provider:
  rxdart:
  simple_logger:
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  image_test_utils:
  pedantic_mono:
flutter:
  uses-material-design: true