name: wdb106_sample
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true